#https://docs.docker.com/reference/compose-file/services/

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx_cont
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html

  wordpress:
    build: requirements/wordpress/.
    container_name: wp_cont
    volumes:
      - ./web:/var/www/html


  
